# Generated by Django 6.1 on 2026-08-27 19:22

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailySheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('transaction_date', models.DateField(db_index=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('APPROVED', 'Approved'), ('RETURNED', 'Returned'), ('REOPENED', 'Reopened')], default='DRAFT', max_length=20)),
                ('incoming_funds', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('tax', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('reconciliation_note', models.TextField(blank=True)),
                ('return_comment', models.TextField(blank=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('returned_at', models.DateTimeField(blank=True, null=True)),
                ('reopened_at', models.DateTimeField(blank=True, null=True)),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='daily_sheets', to='core.agency')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='approved_daily_sheets', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_daily_sheets', to=settings.AUTH_USER_MODEL)),
                ('reopened_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reopened_daily_sheets', to=settings.AUTH_USER_MODEL)),
                ('returned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='returned_daily_sheets', to=settings.AUTH_USER_MODEL)),
                ('submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='submitted_daily_sheets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-transaction_date', 'agency__name'],
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('SHEET_CREATED', 'Sheet created'), ('TRANSACTION_CREATED', 'Transaction created'), ('TRANSACTION_UPDATED', 'Transaction updated'), ('TRANSACTION_DELETED', 'Transaction deleted'), ('OMITTED_TERMINAL_RECORDED', 'Omitted terminal recorded'), ('OMITTED_TERMINAL_REMOVED', 'Omitted terminal removed'), ('SHEET_SUBMITTED', 'Sheet submitted'), ('SHEET_RETURNED', 'Sheet returned'), ('SHEET_APPROVED', 'Sheet approved'), ('SHEET_REOPENED', 'Sheet reopened'), ('INCOMING_FUNDS_CHANGED', 'Incoming funds changed'), ('TAX_CHANGED', 'Tax changed')], max_length=40)),
                ('model_name', models.CharField(max_length=120)),
                ('object_id', models.CharField(max_length=80)),
                ('old_values', models.JSONField(blank=True, default=dict)),
                ('new_values', models.JSONField(blank=True, default=dict)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='audit_logs', to='core.agency')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
                ('daily_sheet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='core.dailysheet')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='DailySheetGame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_name_snapshot', models.CharField(max_length=120)),
                ('closing_time_snapshot', models.TimeField()),
                ('draw_time_snapshot', models.TimeField()),
                ('display_order', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('daily_sheet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sheet_games', to='core.dailysheet')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='daily_sheet_games', to='core.game')),
            ],
            options={
                'ordering': ['daily_sheet', 'display_order', 'closing_time_snapshot', 'id'],
            },
        ),
        migrations.CreateModel(
            name='OmittedTerminal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reason', models.TextField()),
                ('daily_sheet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='omitted_terminals', to='core.dailysheet')),
                ('recorded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recorded_terminal_omissions', to=settings.AUTH_USER_MODEL)),
                ('tpm_code', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='omissions', to='core.tpmcode')),
            ],
            options={
                'ordering': ['tpm_code__code'],
            },
        ),
        migrations.CreateModel(
            name='TPMDailyTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('person_name_snapshot', models.CharField(max_length=255)),
                ('agent_type_snapshot', models.CharField(choices=[('MAIN_AGENT', 'Main Agent'), ('SUBAGENT', 'Subagent')], max_length=20)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_tpm_transactions', to=settings.AUTH_USER_MODEL)),
                ('daily_sheet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='core.dailysheet')),
                ('tpm_code', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='daily_transactions', to='core.tpmcode')),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='updated_tpm_transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['person_name_snapshot', 'tpm_code__code'],
            },
        ),
        migrations.CreateModel(
            name='TransactionGameSale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('daily_sheet_game', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transaction_sales', to='core.dailysheetgame')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales', to='core.tpmdailytransaction')),
            ],
            options={
                'ordering': ['daily_sheet_game__display_order', 'daily_sheet_game__id'],
            },
        ),
        migrations.AddIndex(
            model_name='dailysheet',
            index=models.Index(fields=['agency', 'transaction_date'], name='core_dailys_agency__0a32bc_idx'),
        ),
        migrations.AddIndex(
            model_name='dailysheet',
            index=models.Index(fields=['status', 'transaction_date'], name='core_dailys_status_a2e2ad_idx'),
        ),
        migrations.AddIndex(
            model_name='dailysheet',
            index=models.Index(fields=['created_by', 'transaction_date'], name='core_dailys_created_b11b8d_idx'),
        ),
        migrations.AddConstraint(
            model_name='dailysheet',
            constraint=models.UniqueConstraint(fields=('agency', 'transaction_date'), name='unique_daily_sheet_agency_date'),
        ),
        migrations.AddConstraint(
            model_name='dailysheet',
            constraint=models.CheckConstraint(condition=models.Q(('incoming_funds__gte', 0), ('incoming_funds__isnull', True), _connector='OR'), name='daily_sheet_incoming_funds_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='dailysheet',
            constraint=models.CheckConstraint(condition=models.Q(('tax__gte', 0), ('tax__isnull', True), _connector='OR'), name='daily_sheet_tax_non_negative'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['agency', 'created_at'], name='core_auditl_agency__d6a2c4_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['daily_sheet', 'created_at'], name='core_auditl_daily_s_502c22_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['action', 'created_at'], name='core_auditl_action_29a2bf_idx'),
        ),
        migrations.AddIndex(
            model_name='dailysheetgame',
            index=models.Index(fields=['daily_sheet', 'display_order'], name='core_dailys_daily_s_9db49e_idx'),
        ),
        migrations.AddConstraint(
            model_name='dailysheetgame',
            constraint=models.UniqueConstraint(fields=('daily_sheet', 'game'), name='unique_daily_sheet_game'),
        ),
        migrations.AddIndex(
            model_name='omittedterminal',
            index=models.Index(fields=['daily_sheet', 'tpm_code'], name='core_omitte_daily_s_ab40b9_idx'),
        ),
        migrations.AddConstraint(
            model_name='omittedterminal',
            constraint=models.UniqueConstraint(fields=('daily_sheet', 'tpm_code'), name='unique_omitted_terminal_per_sheet'),
        ),
        migrations.AddIndex(
            model_name='tpmdailytransaction',
            index=models.Index(fields=['daily_sheet', 'tpm_code'], name='core_tpmdai_daily_s_0a368e_idx'),
        ),
        migrations.AddIndex(
            model_name='tpmdailytransaction',
            index=models.Index(fields=['daily_sheet', 'agent_type_snapshot'], name='core_tpmdai_daily_s_7ba613_idx'),
        ),
        migrations.AddConstraint(
            model_name='tpmdailytransaction',
            constraint=models.UniqueConstraint(fields=('daily_sheet', 'tpm_code'), name='unique_tpm_transaction_per_sheet'),
        ),
        migrations.AddIndex(
            model_name='transactiongamesale',
            index=models.Index(fields=['transaction', 'daily_sheet_game'], name='core_transa_transac_d24296_idx'),
        ),
        migrations.AddConstraint(
            model_name='transactiongamesale',
            constraint=models.UniqueConstraint(fields=('transaction', 'daily_sheet_game'), name='unique_transaction_game_sale'),
        ),
        migrations.AddConstraint(
            model_name='transactiongamesale',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gte', 0)), name='transaction_game_sale_amount_non_negative'),
        ),
    ]
