# Generated by Django 6.1 on 2026-08-27 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_dailysheet_auditlog_dailysheetgame_omittedterminal_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailysheet',
            name='reopen_reason',
            field=models.TextField(blank=True),
        ),
    ]
