# Generated by Django 6.1 on 2026-08-27 20:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_dailysheet_reopen_reason'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='agency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='audit_logs', to='core.agency'),
        ),
    ]
