# Generated by Django 6.1 on 2026-08-31 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_phase4_tpm_uniqueness_omission_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('SHEET_CREATED', 'Sheet created'), ('TRANSACTION_CREATED', 'Transaction created'), ('TRANSACTION_UPDATED', 'Transaction updated'), ('TRANSACTION_DELETED', 'Transaction deleted'), ('OMITTED_TERMINAL_RECORDED', 'Omitted terminal recorded'), ('OMITTED_TERMINAL_REMOVED', 'Omitted terminal removed'), ('SHEET_SUBMITTED', 'Sheet submitted'), ('SHEET_RETURNED', 'Sheet returned'), ('SHEET_APPROVED', 'Sheet approved'), ('SHEET_REOPENED', 'Sheet reopened'), ('INCOMING_FUNDS_CHANGED', 'Incoming funds changed'), ('TAX_CHANGED', 'Tax changed'), ('REPORT_PREVIEWED', 'Report previewed'), ('REPORT_EXPORTED', 'Report exported')], max_length=40),
        ),
    ]
