# Generated by Django 6.1 on 2026-09-01 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_auditlog_action'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dailysheetgame',
            options={'ordering': ['daily_sheet', 'display_order', 'id']},
        ),
        migrations.AlterModelOptions(
            name='weeklygameschedule',
            options={'ordering': ['weekday', 'display_order', 'id']},
        ),
        migrations.AddField(
            model_name='dailysheetgame',
            name='is_whole_day_snapshot',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='weeklygameschedule',
            name='is_whole_day',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('SHEET_CREATED', 'Sheet created'), ('TRANSACTION_CREATED', 'Transaction created'), ('TRANSACTION_UPDATED', 'Transaction updated'), ('TRANSACTION_DELETED', 'Transaction deleted'), ('OMITTED_TERMINAL_RECORDED', 'Omitted terminal recorded'), ('OMITTED_TERMINAL_REMOVED', 'Omitted terminal removed'), ('SHEET_SUBMITTED', 'Sheet submitted'), ('SHEET_RETURNED', 'Sheet returned'), ('SHEET_APPROVED', 'Sheet approved'), ('SHEET_REOPENED', 'Sheet reopened'), ('INCOMING_FUNDS_CHANGED', 'Incoming funds changed'), ('TAX_CHANGED', 'Tax changed'), ('REPORT_PREVIEWED', 'Report previewed'), ('REPORT_EXPORTED', 'Report exported'), ('SCHEDULE_CREATED', 'Schedule created'), ('SCHEDULE_UPDATED', 'Schedule updated'), ('SCHEDULE_ACTIVATED', 'Schedule activated'), ('SCHEDULE_DEACTIVATED', 'Schedule deactivated')], max_length=40),
        ),
        migrations.AlterField(
            model_name='dailysheetgame',
            name='closing_time_snapshot',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dailysheetgame',
            name='draw_time_snapshot',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='weeklygameschedule',
            name='closing_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='weeklygameschedule',
            name='draw_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
