# Generated by Django 6.1 on 2026-09-01 21:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_dailysheetgame_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('SHEET_CREATED', 'Sheet created'), ('TRANSACTION_CREATED', 'Transaction created'), ('TRANSACTION_UPDATED', 'Transaction updated'), ('TRANSACTION_DELETED', 'Transaction deleted'), ('OMITTED_TERMINAL_RECORDED', 'Omitted terminal recorded'), ('OMITTED_TERMINAL_REMOVED', 'Omitted terminal removed'), ('SHEET_SUBMITTED', 'Sheet submitted'), ('SHEET_RETURNED', 'Sheet returned'), ('SHEET_APPROVED', 'Sheet approved'), ('SHEET_REOPENED', 'Sheet reopened'), ('INCOMING_FUNDS_CHANGED', 'Incoming funds changed'), ('TAX_CHANGED', 'Tax changed'), ('REPORT_PREVIEWED', 'Report previewed'), ('REPORT_EXPORTED', 'Report exported'), ('SCHEDULE_CREATED', 'Schedule created'), ('SCHEDULE_UPDATED', 'Schedule updated'), ('SCHEDULE_ACTIVATED', 'Schedule activated'), ('SCHEDULE_DEACTIVATED', 'Schedule deactivated'), ('IMPORT_PREVIEWED', 'Import previewed'), ('IMPORT_CONFIRMED', 'Import confirmed'), ('IMPORT_CANCELLED', 'Import cancelled'), ('IMPORT_FAILED', 'Import failed')], max_length=40),
        ),
        migrations.CreateModel(
            name='DailySheetImportBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('transaction_date', models.DateField(db_index=True)),
                ('original_filename', models.CharField(max_length=255)),
                ('file_hash', models.CharField(db_index=True, max_length=64)),
                ('status', models.CharField(choices=[('PREVIEWED', 'Previewed'), ('CONFIRMED', 'Confirmed'), ('CANCELLED', 'Cancelled'), ('FAILED', 'Failed'), ('EXPIRED', 'Expired')], default='PREVIEWED', max_length=20)),
                ('preview_payload', models.JSONField(default=dict)),
                ('warnings', models.JSONField(default=list)),
                ('errors', models.JSONField(default=list)),
                ('existing_transaction_count', models.PositiveIntegerField(default=0)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='daily_sheet_import_batches', to='core.agency')),
                ('confirmed_sheet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='confirmed_import_batches', to='core.dailysheet')),
                ('existing_sheet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='import_batches', to='core.dailysheet')),
                ('uploader', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='daily_sheet_import_batches', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['uploader', 'status'], name='core_dailys_uploade_afbf74_idx'), models.Index(fields=['agency', 'transaction_date'], name='core_dailys_agency__016e8d_idx')],
            },
        ),
    ]
