# Generated by Django 6.1 on 2026-09-16 14:14

import django.db.models.deletion
import django.db.models.functions.text
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_dailysheet_is_archived_alter_auditlog_action_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tpmdailytransaction',
            name='terminal_number_snapshot',
            field=models.CharField(blank=True, default='', editable=False, max_length=80),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('TERMINAL_CREATED', 'Terminal created'), ('TERMINAL_EDITED', 'Terminal edited'), ('TERMINAL_DEACTIVATED', 'Terminal deactivated'), ('TERMINAL_REACTIVATED', 'Terminal reactivated'), ('TERMINAL_REASSIGNED', 'Terminal reassigned'), ('TERMINAL_IMPORT_PREVIEWED', 'Terminal import previewed'), ('TERMINAL_IMPORT_CONFIRMED', 'Terminal import confirmed'), ('TERMINAL_IMPORT_CANCELLED', 'Terminal import cancelled'), ('DAILY_SHEET_RESET', 'Daily sheet reset'), ('DAILY_SHEET_DELETED', 'Daily sheet deleted'), ('SHEET_CREATED', 'Sheet created'), ('TRANSACTION_CREATED', 'Transaction created'), ('TRANSACTION_UPDATED', 'Transaction updated'), ('TRANSACTION_DELETED', 'Transaction deleted'), ('OMITTED_TERMINAL_RECORDED', 'Omitted terminal recorded'), ('OMITTED_TERMINAL_REMOVED', 'Omitted terminal removed'), ('SHEET_SUBMITTED', 'Sheet submitted'), ('SHEET_RETURNED', 'Sheet returned'), ('SHEET_APPROVED', 'Sheet approved'), ('SHEET_REOPENED', 'Sheet reopened'), ('INCOMING_FUNDS_CHANGED', 'Incoming funds changed'), ('TAX_CHANGED', 'Tax changed'), ('REPORT_PREVIEWED', 'Report previewed'), ('REPORT_EXPORTED', 'Report exported'), ('SCHEDULE_CREATED', 'Schedule created'), ('SCHEDULE_UPDATED', 'Schedule updated'), ('SCHEDULE_ACTIVATED', 'Schedule activated'), ('SCHEDULE_DEACTIVATED', 'Schedule deactivated'), ('IMPORT_PREVIEWED', 'Import previewed'), ('IMPORT_CONFIRMED', 'Import confirmed'), ('IMPORT_CANCELLED', 'Import cancelled'), ('IMPORT_FAILED', 'Import failed')], max_length=40),
        ),
        migrations.CreateModel(
            name='TerminalImportBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('original_filename', models.CharField(max_length=255)),
                ('file_hash', models.CharField(max_length=64)),
                ('status', models.CharField(choices=[('PREVIEWED', 'Previewed'), ('CONFIRMED', 'Confirmed'), ('CANCELLED', 'Cancelled')], default='PREVIEWED', max_length=20)),
                ('preview_payload', models.JSONField(default=dict)),
                ('warnings', models.JSONField(default=list)),
                ('errors', models.JSONField(default=list)),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('result_counts', models.JSONField(default=dict)),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='terminal_import_batches', to='core.agency')),
                ('uploader', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='terminal_import_batches', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['uploader', 'status'], name='core_termin_uploade_4aa535_idx'), models.Index(fields=['agency', 'created_at'], name='core_termin_agency__8e7d1c_idx')],
            },
        ),
        migrations.CreateModel(
            name='TerminalNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('terminal_number', models.CharField(max_length=80)),
                ('is_active', models.BooleanField(default=True)),
                ('deactivated_at', models.DateTimeField(blank=True, null=True)),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='terminal_numbers', to='core.agency')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_terminal_numbers', to=settings.AUTH_USER_MODEL)),
                ('deactivated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='deactivated_terminal_numbers', to=settings.AUTH_USER_MODEL)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='terminal_numbers', to='core.person')),
                ('sub_agent_number', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='terminal_numbers', to='core.tpmcode')),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='updated_terminal_numbers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['terminal_number', 'id'],
                'indexes': [models.Index(fields=['agency', 'is_active'], name='core_termin_agency__13f578_idx'), models.Index(fields=['person', 'is_active'], name='core_termin_person__918502_idx')],
                'constraints': [models.UniqueConstraint(django.db.models.functions.text.Lower('terminal_number'), name='terminal_number_ci_unique'), models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('sub_agent_number',), name='one_active_terminal_per_sub_agent'), models.CheckConstraint(condition=models.Q(('terminal_number', ''), _negated=True), name='terminal_number_not_empty')],
            },
        ),
    ]
