# Generated by Django 6.1 on 2026-09-16 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_terminal_number_register'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tpmcode',
            options={'ordering': ['code'], 'verbose_name': 'Sub-Agent Number', 'verbose_name_plural': 'Sub-Agent Numbers'},
        ),
    ]
