# Generated by Django 6.1 on 2026-09-23 11:00

import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_sub_agent_display_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('AGENCY_CREATED', 'Agency created'), ('AGENCY_UPDATED', 'Agency updated'), ('AGENCY_DEACTIVATED', 'Agency deactivated'), ('AGENCY_REACTIVATED', 'Agency reactivated'), ('TERMINAL_CREATED', 'Terminal created'), ('TERMINAL_EDITED', 'Terminal edited'), ('TERMINAL_DEACTIVATED', 'Terminal deactivated'), ('TERMINAL_REACTIVATED', 'Terminal reactivated'), ('TERMINAL_REASSIGNED', 'Terminal reassigned'), ('TERMINAL_IMPORT_PREVIEWED', 'Terminal import previewed'), ('TERMINAL_IMPORT_CONFIRMED', 'Terminal import confirmed'), ('TERMINAL_IMPORT_CANCELLED', 'Terminal import cancelled'), ('DAILY_SHEET_RESET', 'Daily sheet reset'), ('DAILY_SHEET_DELETED', 'Daily sheet deleted'), ('SHEET_CREATED', 'Sheet created'), ('TRANSACTION_CREATED', 'Transaction created'), ('TRANSACTION_UPDATED', 'Transaction updated'), ('TRANSACTION_DELETED', 'Transaction deleted'), ('OMITTED_TERMINAL_RECORDED', 'Omitted terminal recorded'), ('OMITTED_TERMINAL_REMOVED', 'Omitted terminal removed'), ('SHEET_SUBMITTED', 'Sheet submitted'), ('SHEET_RETURNED', 'Sheet returned'), ('SHEET_APPROVED', 'Sheet approved'), ('SHEET_REOPENED', 'Sheet reopened'), ('INCOMING_FUNDS_CHANGED', 'Incoming funds changed'), ('TAX_CHANGED', 'Tax changed'), ('REPORT_PREVIEWED', 'Report previewed'), ('REPORT_EXPORTED', 'Report exported'), ('SCHEDULE_CREATED', 'Schedule created'), ('SCHEDULE_UPDATED', 'Schedule updated'), ('SCHEDULE_ACTIVATED', 'Schedule activated'), ('SCHEDULE_DEACTIVATED', 'Schedule deactivated'), ('IMPORT_PREVIEWED', 'Import previewed'), ('IMPORT_CONFIRMED', 'Import confirmed'), ('IMPORT_CANCELLED', 'Import cancelled'), ('IMPORT_FAILED', 'Import failed')], max_length=40),
        ),
        migrations.AddConstraint(
            model_name='agency',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('name'), name='agency_name_ci_unique'),
        ),
        migrations.AddConstraint(
            model_name='agency',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('code'), name='agency_code_ci_unique'),
        ),
    ]
