# Generated by Django 6.1 on 2026-09-24 11:21

import django.db.models.deletion
import django.db.models.functions.text
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_auditlog_action_agency_agency_name_ci_unique_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('AGENCY_CREATED', 'Agency created'), ('AGENCY_UPDATED', 'Agency updated'), ('AGENCY_DEACTIVATED', 'Agency deactivated'), ('AGENCY_REACTIVATED', 'Agency reactivated'), ('TERMINAL_CREATED', 'Terminal created'), ('TERMINAL_EDITED', 'Terminal edited'), ('TERMINAL_DEACTIVATED', 'Terminal deactivated'), ('TERMINAL_REACTIVATED', 'Terminal reactivated'), ('TERMINAL_REASSIGNED', 'Terminal reassigned'), ('TERMINAL_IMPORT_PREVIEWED', 'Terminal import previewed'), ('TERMINAL_IMPORT_CONFIRMED', 'Terminal import confirmed'), ('TERMINAL_IMPORT_CANCELLED', 'Terminal import cancelled'), ('DAILY_SHEET_RESET', 'Daily sheet reset'), ('DAILY_SHEET_DELETED', 'Daily sheet deleted'), ('SHEET_CREATED', 'Sheet created'), ('TRANSACTION_CREATED', 'Transaction created'), ('TRANSACTION_UPDATED', 'Transaction updated'), ('TRANSACTION_DELETED', 'Transaction deleted'), ('OMITTED_TERMINAL_RECORDED', 'Omitted terminal recorded'), ('OMITTED_TERMINAL_REMOVED', 'Omitted terminal removed'), ('SHEET_SUBMITTED', 'Sheet submitted'), ('SHEET_RETURNED', 'Sheet returned'), ('SHEET_APPROVED', 'Sheet approved'), ('SHEET_REOPENED', 'Sheet reopened'), ('INCOMING_FUNDS_CHANGED', 'Incoming funds changed'), ('TAX_CHANGED', 'Tax changed'), ('REPORT_PREVIEWED', 'Report previewed'), ('REPORT_EXPORTED', 'Report exported'), ('SCHEDULE_CREATED', 'Schedule created'), ('SCHEDULE_UPDATED', 'Schedule updated'), ('SCHEDULE_ACTIVATED', 'Schedule activated'), ('SCHEDULE_DEACTIVATED', 'Schedule deactivated'), ('IMPORT_PREVIEWED', 'Import previewed'), ('IMPORT_CONFIRMED', 'Import confirmed'), ('IMPORT_CANCELLED', 'Import cancelled'), ('IMPORT_FAILED', 'Import failed'), ('PAYMENT_PAYER_CREATED', 'Payment payer created'), ('PAYMENT_PAYER_UPDATED', 'Payment payer updated'), ('PAYMENT_PAYER_DEACTIVATED', 'Payment payer deactivated'), ('PAYMENT_PAYER_REACTIVATED', 'Payment payer reactivated'), ('PAYER_SUBAGENT_ASSIGNED', 'Sub-agent assigned'), ('PAYER_SUBAGENT_UNASSIGNED', 'Sub-agent unassigned'), ('PAYER_SUBAGENT_REASSIGNED', 'Sub-agent reassigned'), ('PAYMENT_OBLIGATION_CREATED', 'Payment obligation created'), ('PAYMENT_OBLIGATION_UPDATED', 'Payment obligation updated'), ('PAYMENT_OBLIGATION_CANCELLED', 'Payment obligation cancelled'), ('PAYMENT_RECORDED', 'Payment recorded'), ('PAYMENT_REVERSED', 'Payment reversed')], max_length=40),
        ),
        migrations.CreateModel(
            name='PaymentPayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('payer_name', models.CharField(max_length=200)),
                ('telephone', models.CharField(blank=True, default='', max_length=80)),
                ('email', models.EmailField(blank=True, default='', max_length=255)),
                ('address', models.TextField(blank=True, default='')),
                ('notes', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(default=True)),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payment_payers', to='core.agency')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_payment_payers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['payer_name', 'id'],
            },
        ),
        migrations.CreateModel(
            name='PaymentObligation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('obligation_number', models.CharField(max_length=40, unique=True)),
                ('description', models.CharField(max_length=255)),
                ('obligation_date', models.DateField()),
                ('due_date', models.DateField(blank=True, null=True)),
                ('total_expected', models.DecimalField(decimal_places=2, max_digits=14)),
                ('notes', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('PARTIALLY_PAID', 'Partially Paid'), ('PAID', 'Paid'), ('CANCELLED', 'Cancelled')], default='OPEN', max_length=20)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('cancellation_reason', models.TextField(blank=True, default='')),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payment_obligations', to='core.agency')),
                ('cancelled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cancelled_payment_obligations', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_payment_obligations', to=settings.AUTH_USER_MODEL)),
                ('payer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='obligations', to='core.paymentpayer')),
            ],
            options={
                'ordering': ['-obligation_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='PayerSubAgentAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('assigned_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('unassigned_at', models.DateTimeField(blank=True, null=True)),
                ('reassignment_reason', models.TextField(blank=True, default='')),
                ('assigned_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assigned_payment_sub_agents', to=settings.AUTH_USER_MODEL)),
                ('sub_agent_number', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payment_payer_assignments', to='core.tpmcode')),
                ('unassigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='unassigned_payment_sub_agents', to=settings.AUTH_USER_MODEL)),
                ('payer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_agent_assignments', to='core.paymentpayer')),
            ],
            options={
                'ordering': ['payer__payer_name', 'sub_agent_number__code'],
            },
        ),
        migrations.CreateModel(
            name='PayerPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('receipt_number', models.CharField(max_length=40, unique=True)),
                ('agency_snapshot', models.CharField(max_length=200)),
                ('payer_name_snapshot', models.CharField(max_length=200)),
                ('linked_sub_agent_numbers_snapshot', models.JSONField(default=list)),
                ('obligation_number_snapshot', models.CharField(max_length=40)),
                ('obligation_description_snapshot', models.CharField(max_length=255)),
                ('obligation_date_snapshot', models.DateField()),
                ('expected_amount_snapshot', models.DecimalField(decimal_places=2, max_digits=14)),
                ('amount_previously_paid', models.DecimalField(decimal_places=2, max_digits=14)),
                ('amount_received', models.DecimalField(decimal_places=2, max_digits=14)),
                ('cumulative_amount_paid', models.DecimalField(decimal_places=2, max_digits=14)),
                ('balance_after_payment', models.DecimalField(decimal_places=2, max_digits=14)),
                ('payment_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('payment_method', models.CharField(choices=[('CASH', 'Cash'), ('MOBILE_MONEY', 'Mobile Money'), ('BANK_TRANSFER', 'Bank Transfer'), ('CHEQUE', 'Cheque'), ('OTHER', 'Other')], max_length=20)),
                ('payment_reference', models.CharField(blank=True, default='', max_length=120)),
                ('notes', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('POSTED', 'Posted'), ('REVERSED', 'Reversed')], default='POSTED', max_length=20)),
                ('idempotency_key', models.CharField(max_length=100, unique=True)),
                ('reversed_at', models.DateTimeField(blank=True, null=True)),
                ('reversal_reason', models.TextField(blank=True, default='')),
                ('recorded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recorded_payer_payments', to=settings.AUTH_USER_MODEL)),
                ('reversed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reversed_payer_payments', to=settings.AUTH_USER_MODEL)),
                ('obligation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='core.paymentobligation')),
            ],
            options={
                'ordering': ['-payment_date', '-id'],
                'indexes': [models.Index(fields=['obligation', 'status', 'payment_date'], name='core_payerp_obligat_bef23d_idx'), models.Index(fields=['idempotency_key'], name='core_payerp_idempot_bccfa9_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='paymentpayer',
            index=models.Index(fields=['agency', 'is_active', 'payer_name'], name='core_paymen_agency__8086f9_idx'),
        ),
        migrations.AddConstraint(
            model_name='paymentpayer',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('payer_name'), models.F('agency'), name='unique_payment_payer_name_per_agency'),
        ),
        migrations.AddConstraint(
            model_name='paymentpayer',
            constraint=models.CheckConstraint(condition=models.Q(('payer_name', ''), _negated=True), name='payment_payer_name_not_empty'),
        ),
        migrations.AddIndex(
            model_name='paymentobligation',
            index=models.Index(fields=['agency', 'status', 'obligation_date'], name='core_paymen_agency__7fdbf2_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentobligation',
            index=models.Index(fields=['payer', 'obligation_date'], name='core_paymen_payer_i_d91a15_idx'),
        ),
        migrations.AddIndex(
            model_name='payersubagentassignment',
            index=models.Index(fields=['payer', 'is_active'], name='core_payers_payer_i_3bbee5_idx'),
        ),
        migrations.AddIndex(
            model_name='payersubagentassignment',
            index=models.Index(fields=['sub_agent_number', 'is_active'], name='core_payers_sub_age_6110a7_idx'),
        ),
        migrations.AddConstraint(
            model_name='payersubagentassignment',
            constraint=models.UniqueConstraint(fields=('payer', 'sub_agent_number'), name='unique_payer_sub_agent_assignment'),
        ),
        migrations.AddConstraint(
            model_name='payersubagentassignment',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('sub_agent_number',), name='unique_active_payer_sub_agent_assignment'),
        ),
    ]
