# Generated by Django 6.1 on 2026-09-24 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_auditlog_action_paymentpayer_paymentobligation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payerpayment',
            name='linked_sub_agent_numbers_snapshot',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
