# Generated by Django 6.1 on 2026-09-24 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_alter_payerpayment_linked_sub_agent_numbers_snapshot'),
    ]

    operations = [
        migrations.AddField(
            model_name='payerpayment',
            name='recorded_by_display_snapshot',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.CreateModel(
            name='PaymentNumberSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence_type', models.CharField(max_length=20)),
                ('year', models.PositiveIntegerField()),
                ('last_value', models.PositiveIntegerField(default=0)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('sequence_type', 'year'), name='unique_payment_number_sequence')],
            },
        ),
    ]
