# Generated by Django 6.1 on 2026-09-24 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_payerpayment_recorded_by_display_snapshot_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payerpayment',
            name='recorded_by_display_snapshot',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
