# Generated by Django 6.1 on 2026-09-24 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_alter_payerpayment_recorded_by_display_snapshot'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='payerpayment',
            constraint=models.CheckConstraint(condition=models.Q(('expected_amount_snapshot__gt', 0)), name='payment_expected_snapshot_positive'),
        ),
        migrations.AddConstraint(
            model_name='payerpayment',
            constraint=models.CheckConstraint(condition=models.Q(('amount_previously_paid__gte', 0)), name='payment_previous_paid_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='payerpayment',
            constraint=models.CheckConstraint(condition=models.Q(('amount_received__gt', 0)), name='payment_amount_received_positive'),
        ),
        migrations.AddConstraint(
            model_name='payerpayment',
            constraint=models.CheckConstraint(condition=models.Q(('cumulative_amount_paid__gte', 0)), name='payment_cumulative_paid_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='payerpayment',
            constraint=models.CheckConstraint(condition=models.Q(('balance_after_payment__gte', 0)), name='payment_balance_after_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='payerpayment',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('reversal_reason', ''), ('reversed_at__isnull', True), ('reversed_by__isnull', True), ('status', 'POSTED')), models.Q(('reversed_at__isnull', False), ('reversed_by__isnull', False), ('status', 'REVERSED'), models.Q(('reversal_reason', ''), _negated=True)), _connector='OR'), name='payment_reversal_metadata_consistent'),
        ),
        migrations.AddConstraint(
            model_name='paymentobligation',
            constraint=models.CheckConstraint(condition=models.Q(('total_expected__gt', 0)), name='payment_obligation_total_expected_positive'),
        ),
    ]
