# Generated by Django 6.1 on 2026-09-26 20:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_payerpayment_payment_expected_snapshot_positive_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailysheet',
            name='holiday_name_snapshot',
            field=models.CharField(blank=True, default='', max_length=160),
        ),
        migrations.AddField(
            model_name='dailysheet',
            name='holiday_normal_game_name_snapshot',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='dailysheet',
            name='holiday_override_applied',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='dailysheet',
            name='holiday_override_id_snapshot',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dailysheet',
            name='holiday_replacement_game_name_snapshot',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='dailysheet',
            name='holiday_source_date_snapshot',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dailysheetgame',
            name='is_holiday_override_snapshot',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('AGENCY_CREATED', 'Agency created'), ('AGENCY_UPDATED', 'Agency updated'), ('AGENCY_DEACTIVATED', 'Agency deactivated'), ('AGENCY_REACTIVATED', 'Agency reactivated'), ('TERMINAL_CREATED', 'Terminal created'), ('TERMINAL_EDITED', 'Terminal edited'), ('TERMINAL_DEACTIVATED', 'Terminal deactivated'), ('TERMINAL_REACTIVATED', 'Terminal reactivated'), ('TERMINAL_REASSIGNED', 'Terminal reassigned'), ('TERMINAL_IMPORT_PREVIEWED', 'Terminal import previewed'), ('TERMINAL_IMPORT_CONFIRMED', 'Terminal import confirmed'), ('TERMINAL_IMPORT_CANCELLED', 'Terminal import cancelled'), ('DAILY_SHEET_RESET', 'Daily sheet reset'), ('DAILY_SHEET_DELETED', 'Daily sheet deleted'), ('SHEET_CREATED', 'Sheet created'), ('TRANSACTION_CREATED', 'Transaction created'), ('TRANSACTION_UPDATED', 'Transaction updated'), ('TRANSACTION_DELETED', 'Transaction deleted'), ('OMITTED_TERMINAL_RECORDED', 'Omitted terminal recorded'), ('OMITTED_TERMINAL_REMOVED', 'Omitted terminal removed'), ('SHEET_SUBMITTED', 'Sheet submitted'), ('SHEET_RETURNED', 'Sheet returned'), ('SHEET_APPROVED', 'Sheet approved'), ('SHEET_REOPENED', 'Sheet reopened'), ('INCOMING_FUNDS_CHANGED', 'Incoming funds changed'), ('TAX_CHANGED', 'Tax changed'), ('REPORT_PREVIEWED', 'Report previewed'), ('REPORT_EXPORTED', 'Report exported'), ('SCHEDULE_CREATED', 'Schedule created'), ('SCHEDULE_UPDATED', 'Schedule updated'), ('SCHEDULE_ACTIVATED', 'Schedule activated'), ('SCHEDULE_DEACTIVATED', 'Schedule deactivated'), ('HOLIDAY_OVERRIDE_CREATED', 'Holiday override created'), ('HOLIDAY_OVERRIDE_UPDATED', 'Holiday override updated'), ('HOLIDAY_OVERRIDE_ACTIVATED', 'Holiday override activated'), ('HOLIDAY_OVERRIDE_DEACTIVATED', 'Holiday override deactivated'), ('HOLIDAY_OVERRIDE_CANCELLED', 'Holiday override cancelled'), ('IMPORT_PREVIEWED', 'Import previewed'), ('IMPORT_CONFIRMED', 'Import confirmed'), ('IMPORT_CANCELLED', 'Import cancelled'), ('IMPORT_FAILED', 'Import failed'), ('PAYMENT_PAYER_CREATED', 'Payment payer created'), ('PAYMENT_PAYER_UPDATED', 'Payment payer updated'), ('PAYMENT_PAYER_DEACTIVATED', 'Payment payer deactivated'), ('PAYMENT_PAYER_REACTIVATED', 'Payment payer reactivated'), ('PAYER_SUBAGENT_ASSIGNED', 'Sub-agent assigned'), ('PAYER_SUBAGENT_UNASSIGNED', 'Sub-agent unassigned'), ('PAYER_SUBAGENT_REASSIGNED', 'Sub-agent reassigned'), ('PAYMENT_OBLIGATION_CREATED', 'Payment obligation created'), ('PAYMENT_OBLIGATION_UPDATED', 'Payment obligation updated'), ('PAYMENT_OBLIGATION_CANCELLED', 'Payment obligation cancelled'), ('PAYMENT_RECORDED', 'Payment recorded'), ('PAYMENT_REVERSED', 'Payment reversed')], max_length=40),
        ),
        migrations.CreateModel(
            name='HolidayGameOverride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('holiday_date', models.DateField(db_index=True)),
                ('holiday_name', models.CharField(max_length=160)),
                ('source_date', models.DateField()),
                ('notes', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(default=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('cancellation_reason', models.TextField(blank=True, default='')),
                ('cancelled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cancelled_holiday_game_overrides', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_holiday_game_overrides', to=settings.AUTH_USER_MODEL)),
                ('normal_game', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='normal_holiday_overrides', to='core.game')),
                ('replacement_game', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='replacement_holiday_overrides', to='core.game')),
            ],
            options={
                'ordering': ['holiday_date', 'id'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('holiday_date',), name='unique_active_holiday_game_override_date'), models.CheckConstraint(condition=models.Q(('holiday_name', ''), _negated=True), name='holiday_override_name_not_empty'), models.CheckConstraint(condition=models.Q(('source_date__lt', models.F('holiday_date'))), name='holiday_override_source_before_holiday')],
            },
        ),
    ]
